version: '3.1'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "
      ./wait-for-postgres.sh db &&
      uvicorn main:app --host 0.0.0.0 --reload
      "
    depends_on:
      - db