version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      db:
        condition: service_healthy
